app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('home.index');
});

//Route for Category
Route::resource('categories','CategoriesController');

//Route for Post
Route::resource('posts','PostsController');

app/models/Category.php
<?php

class Category extends \Eloquent {
	protected $fillable = [];


}

app/controllers/CategoriesController.php
<?php

class CategoriesController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /categories
	 *
	 * @return Response
	 */
	public function index()
	{
		//get all Categories on DB
		$categories = Category::paginate(5);
		//pass Categories of 5
		return View::make('categories.index')->with(compact('categories'));
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /categories/create
	 *
	 * @return Response
	 */
	public function create()
	{
		//get selected columnds
		$cats = Category::all(array('id', 'name'));
		//iterate for array arangement
		foreach ($cats as $cat) {
			//set array 
			$categories[$cat->id] = $cat->name;
		}
		//pass and render array to view
		return View::make('categories.create')->with(compact('categories'));
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /categories
	 *
	 * @return Response
	 */
	public function store()
	{
		//set rules for fields
		$rules = array(
			'name'            => 'Required|max:50',
		);

		// Get all the inputs.
		$inputs = Input::all();

		// Validate the inputs.
		$validator = Validator::make($inputs, $rules);

		// Check if the form validates with success.
		if ($validator->passes()){
			// Create the category.
			$category = new Category;
			$category->name 	= Input::get('name');
			$category->parent_id  = Input::get('parent');
			$category->save();

			// Redirect to the User Index page.
			return Redirect::to('categories')->with('notification', 'Added a Category');
		}

		return Redirect::back()->withInput($inputs)->withErrors($validator->getMessageBag());
	}

	/**
	 * Display the specified resource.
	 * GET /categories/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//get post that has the category id
		$posts = Post::where('categories', 'LIKE', "%$id%")->paginate(5);
		//paginate and render array to view
		return View::make('categories.show')->with(compact('posts'));	
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /categories/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//get all categories
		$cats = Category::all(array('id', 'name'));
		foreach ($cats as $cat) {
			//skip same id as Present Category
			if($cat->id != $id){
				//arrange in a array
				$categories[$cat->id] = $cat->name;
			}
			
		}
		$category = Category::find($id);
		return View::make('categories.edit')->with(compact('category'))->with(compact('categories'));
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /categories/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//set rules
		$rules = array(
			'name'            => 'Required|max:50',
		);

		// Get all the inputs.
		$inputs = Input::all();

		// Validate the inputs.
		$validator = Validator::make($inputs, $rules);

		// Check if the form validates with success.
		if ($validator->passes()){
			// Create the Category.
			$category = Category::find($id);
			$category->name 	= Input::get('name');
			$category->parent_id  = Input::get('parent');
			$category->save();

			// Redirect to the User Index page.
			return Redirect::to('categories')->with('notification', 'Updated a Category');
		}

		return Redirect::back()->withInput($inputs)->withErrors($validator->getMessageBag());
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /categories/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//get single category from DB
		$category = Category::find($id);
		if($category->delete()){
			// Redirect to the categories Index page.
			return Redirect::to('categories')->with('notification', "Category Successfuly Deleted!");
		}else{
			// Redirect to the categories Index page.
			return Redirect::to('categories')->with('notification', "Delete Not Successful");
		}
	}

}

app/views/categories/create.blade.php
@extends('layout.master')
@section('content')
	
	<div class="row-fluid">
		<div class="col-sm-8 col-md-8 col-lg-8 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">
			{{Form::open(array('url' => "categories", 'method' => 'post'))}}
				<legend>Create User</legend>
			
				<div class="form-group">
					{{Form::label('Category Name')}}
					{{Form::text('name', '', array('class' => 'form-control' , 'placeholder' => 'Category Name'))}}
				</div>
				@if($errors->has('name'))
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>{{$errors->first('name')}} </strong>
					</div>
				@endif

				<div class="form-group">
					{{Form::label('Parent Category')}}
					{{Form::select('parent', $categories,'',array('class' => 'form-control'))}}
				</div>
				@if($errors->has('parent'))
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>{{$errors->first('parent')}} </strong>
					</div>
				@endif


				<button type="submit" class="btn btn-primary">Create Category</button>
			{{Form::close()}}
			
		</div>
	</div>

	<div class="clearfix">
	
	</div>

@stop

app/views/categories/edit.blade.php
@extends('layout.master')
@section('content')
	
	<div class="row-fluid">
		<div class="col-sm-8 col-md-8 col-lg-8 col-sm-offset-2 col-md-offset-2 col-lg-offset-2">
			{{Form::open(array('url' => "categories/$category->id", 'method' => 'put'))}}
				<legend>Edit Category</legend>
			
				<div class="form-group">
					{{Form::label('Category Name')}}
					{{Form::text('name', "$category->name", array('class' => 'form-control' , 'placeholder' => 'Category Name'))}}
				</div>
				@if($errors->has('name'))
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>{{$errors->first('name')}} </strong>
					</div>
				@endif

				<div class="form-group">
					{{Form::label('Parent Category')}}
					{{Form::select('parent', $categories,"$category->parent_id",array('class' => 'form-control'))}}
				</div>
				@if($errors->has('parent'))
					<div class="alert alert-danger">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>{{$errors->first('parent')}} </strong>
					</div>
				@endif


				<button type="submit" class="btn btn-primary">Update Category</button>
			{{Form::close()}}
			
		</div>
	</div>

	<div class="clearfix">
	
	</div>

@stop

app/views/categories/index.blade.php
@extends('layout.master')
@section('content')

    <!-- Confirmation -->
    @include('popups.delete_confirmation')
    <!-- ./ Confirmation -->

	<div class="row-fluid">
		<h4>Categories</h4>

		<a href="{{ URL::to('categories/create') }}"  class="btn btn-info" ><span class="glyphicon glyphicon-plus"></span>New Category</a>
		
		<div class="table-responsive">
			<table class="table table-hover ">
				<thead>
					<tr>
						<th>Category ID</th>
						<th>Name</th>
						<th>Parent Category</th>
						<th>Created</th>
						<th>Updated</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach($categories as $category)
					<tr>
						<td>{{$category->id}}</td>
						<td>
							<a href="{{ URL::to("categories/$category->id") }}">{{$category->name}}</a>
						</td>
						<td><?php echo ($category->parent_id != "") ? Category::find($category->parent_id)->name : 'NONE'; ?></td>
						<td>{{date("F j, Y, g:i a",strtotime($category->created_at)) }}</td>
						<td>{{date("F j, Y, g:i a",strtotime($category->updated_at)) }}</td>
						<td>
							<a href='{{URL::to("categories/$category->id/edit")}}'><span class="glyphicon glyphicon-edit"></span></a>
							<a data-href="{{ route('categories.destroy',array($category->id)) }}" data-toggle="modal" data-target="#confirm-delete" href="#"><span class='glyphicon glyphicon-trash'></span></a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>

	<div class="row-fluid  text-center">

		{{$categories->links()}}
		
	</div>

@stop

app/views/categories/show.blade.php
@extends('layout.master')
@section('content')

    <!-- Confirmation -->
    @include('popups.delete_confirmation')
    <!-- ./ Confirmation -->

	<div class="row-fluid">
		<h4>Posts</h4>


		<div class="table-responsive">
			<table class="table table-hover ">
				<thead>
					<tr>
						<th>Post ID</th>
						<th>Title</th>
						<th>Body</th>
						<th>Created</th>
						<th>Updated</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach($posts as $post)
					<tr>
						<td>{{$post->id}}</td>
						<td>
							<a href="{{ URL::to("posts/$post->id") }}">{{$post->title}}</a>	
						</td>
						<td>{{$post->body}}</td>
						<td>{{date("F j, Y, g:i a",strtotime($post->created_at)) }}</td>
						<td>{{date("F j, Y, g:i a",strtotime($post->updated_at)) }}</td>
						<td>
							<a href='{{URL::to("posts/$post->id/edit")}}'><span class="glyphicon glyphicon-edit"></span></a>
							<a data-href="{{ route('posts.destroy',array($post->id)) }}" data-toggle="modal" data-target="#confirm-delete" href="#"><span class='glyphicon glyphicon-trash'></span></a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>

	<div class="row-fluid  text-center">

		{{$posts->links()}}
		
	</div>

@stop